name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  # Windows
  windows-build:
    name: ${{matrix.os}} (${{matrix.dotnet_architecture}} dotnet)
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        dotnet_architecture: [x86, x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dotnet
      shell: pwsh
      run: ./.github/workflows/install-dotnet.ps1 -Architecture ${{matrix.dotnet_architecture}}

    - name: Build
      shell: pwsh
      run: ./build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.os}}-artifacts
        path: ./artifacts

  # Non-Windows
  non-windows-build:
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      shell: pwsh
      run: ./build.ps1

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.os}}-artifacts
        path: ./artifacts
